import {Page, NavController, NavParams} from 'ionic-angular';
import {ItemDetailsPage} from '../item-details/item-details';

var directory = [
 {
   "Type":"Car Service",
   "Name":"Maplecrest Ford Lincoln",
   "Phone":"(908) 964-7700 ",
   "Email":"",
   "Address":"2800 Springfield Ave, Vauxhall, NJ 07088",
   "Website":"",
   "Recommender":"Wei",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Reasonable",
   "Work Quality (Superb, Satisfactory, So-so)":"Superb",
   "Transaction Process (Easy, Ok, Difficult)":"Ok",
   "Review":"Wait is a little long. Over one hour for oil change. Good service."
 },
 {
   "Type":"Car Service",
   "Name":"Route22Toyota",
   "Phone":"(800) 768-1681",
   "Email":"",
   "Address":"109 U.S. 22, Hillside, NJ 07205",
   "Website":"",
   "Recommender":"Wei",
   "Service Used":"",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Fixed a long standing \"Engine Service\" problem other places could not fix"
 },
 {
   "Type":"Cleaning Service",
   "Name":"Alicia",
   "Phone":"(862) 202-9428",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"Surbhi Gupta",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Very thorough cleaning. You have to stick with the appointment. She is busy."
 },
 {
   "Type":"CPA",
   "Name":"Mayank Patel",
   "Phone":"917-996-5059",
   "Email":"mayankpat@gmail.com",
   "Address":"",
   "Website":"",
   "Recommender":"Saurabh Agarwal",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Value",
   "Work Quality (Superb, Satisfactory, So-so)":"Satisfactory",
   "Transaction Process (Easy, Ok, Difficult)":"Ok",
   "Review":"Get job done. Used him for 2015 tax filing. Work through google drive and email. Only issue is that he does not have efiling."
 },
 {
   "Type":"Daycare",
   "Name":"ECYC",
   "Phone":"732-594-3292",
   "Email":"carolyn_sharkey@merck.com",
   "Address":"92 East Grand Ave.\nRahway NJ 07065",
   "Website":"",
   "Recommender":"Wei",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Best facility. Nice people."
 },
 {
   "Type":"Desi Nanny Service Agency",
   "Name":"ZSkillInterchange",
   "Phone":"(646) 683-2449",
   "Email":"zskillinterchange@gmail.com",
   "Address":"",
   "Website":"",
   "Recommender":"Akash Gupta",
   "Service Used":"",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Prompt response. I actually never ended up hiring anyone from there."
 },
 {
   "Type":"Dentist",
   "Name":"Louis Zazzaro",
   "Phone":"(201) 626-6210",
   "Email":"",
   "Address":"100 Pavonia Ave, Jersey City, NJ",
   "Website":"",
   "Recommender":"Janhavi Gupta",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Reasonable",
   "Work Quality (Superb, Satisfactory, So-so)":"Superb",
   "Transaction Process (Easy, Ok, Difficult)":"Ok",
   "Review":"Janhavi and Aditya are using since 5 years. Appointment is absolutely necessary. Good dentist. Does not recommend unnecessary procedures."
 },
 {
   "Type":"Doctor",
   "Name":"Dr. Douglas M. Roth At Summit medical group at Shorthills",
   "Phone":"(908) 277-8759",
   "Email":"",
   "Address":"85 Woodland Rd, Short Hills, NJ 07078",
   "Website":"",
   "Recommender":"Wei",
   "Service Used":"",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Willing to spend time to explain. Comprehensive tests for physical checkups. Good doctor."
 },
 {
   "Type":"Doctor",
   "Name":"Summit Medical Group",
   "Phone":"973-379-4496",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"Saurabh Agarwal",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Reasonable",
   "Work Quality (Superb, Satisfactory, So-so)":"Satisfactory",
   "Transaction Process (Easy, Ok, Difficult)":"Ok",
   "Review":"One place to go for all medical need. "
 },
 {
   "Type":"Garage door",
   "Name":"Jersey Garage Door",
   "Phone":"(732) 499-0311",
   "Email":"",
   "Address":"321 West Ln, Clark, NJ 07066, USA",
   "Website":"",
   "Recommender":"Akash Gupta",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Reasonable",
   "Work Quality (Superb, Satisfactory, So-so)":"Satisfactory",
   "Transaction Process (Easy, Ok, Difficult)":"Ok",
   "Review":"Will charge per visit. Better off explaining door type and problem over phone first. We hired them twice to fix the spring. Once fixed temporarily deferring full replacement for a year."
 },
 {
   "Type":"Handy man",
   "Name":"Don Polombo",
   "Phone":"(973) 796-6533",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"Surbhi Gupta",
   "Service Used":"",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":""
 },
 {
   "Type":"Handy man",
   "Name":"Jose",
   "Phone":"(908) 803-0478",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"Surbhi Gupta",
   "Service Used":"",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Ref from Sarika"
 },
 {
   "Type":"Handy man",
   "Name":"Jai",
   "Phone":"(862) 354-3152",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"Surbhi Gupta",
   "Service Used":"",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Ref from Riteeka"
 },
 {
   "Type":"Handy man",
   "Name":"John",
   "Phone":"(973) 727-8482",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"Surbhi Gupta",
   "Service Used":"",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Ref from handyman John"
 },
 {
   "Type":"Real Estate Attorney",
   "Name":"Milan Patel",
   "Phone":"732-452-9888",
   "Email":"",
   "Address":"1740 Oak Tree Rd # E, Edison, NJ 08820",
   "Website":"",
   "Recommender":"Saurabh Agarwal",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Reasonable",
   "Work Quality (Superb, Satisfactory, So-so)":"Satisfactory",
   "Transaction Process (Easy, Ok, Difficult)":"Ok",
   "Review":"Used his service two times to close the house. He has office on Oak Tree Edison."
 },
 {
   "Type":"Real Estate Attorney",
   "Name":"Avivith Oppenheim",
   "Phone":"",
   "Email":"avivith@avivithoppenheim.com",
   "Address":"211 Mountain Avenue, Springfield",
   "Website":"",
   "Recommender":"Akash Gupta",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Reasonable",
   "Work Quality (Superb, Satisfactory, So-so)":"Satisfactory",
   "Transaction Process (Easy, Ok, Difficult)":"Easy",
   "Review":"Pragmatic. Reasonable responsiveness. Uses paralegal for a lot of work. Overall decent attorney. Helped me negotiate money after inspection. Overall smooth process."
 },
 {
   "Type":"HVAC",
   "Name":"Victor",
   "Phone":"(732) 423-3939",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"Saurabh Gupta",
   "Service Used":"",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":""
 },
 {
   "Type":"Kids Math activity",
   "Name":"Bergen County Academics",
   "Phone":"",
   "Email":"",
   "Address":"200 Hackensack Ave, Hackensack, NJ 07601",
   "Website":"",
   "Recommender":"Wei",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Comprehensive resource of math contests. A math environment cannot be found elsewhere. To join, just go in person. For kids grade 2 and higher. BCA is a top high school in New Jersey. It has a team of math coaches. A student there won gold medal at International Math Olympiad in 2015."
 },
 {
   "Type":"Kids Math activity",
   "Name":"Bergen County Academics",
   "Phone":"",
   "Email":"",
   "Address":"200 Hackensack Ave, Hackensack, NJ 07601",
   "Website":"",
   "Recommender":"Akash Gupta",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Value",
   "Work Quality (Superb, Satisfactory, So-so)":"Satisfactory",
   "Transaction Process (Easy, Ok, Difficult)":"Easy",
   "Review":"Put Aditya in the program in 2015-16 year. Got re-introduced to Beast Academy books. Good program to know about all kinds of math challenge tests such as Kumon. Program starts from Grade 2 onwards. Once a week on Sunday 10am-2pm. Full school year program for ~$350."
 },
 {
   "Type":"Lawnmover",
   "Name":"Edwin",
   "Phone":"(862) 250-1349",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"Saurabh Agarwal",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Value",
   "Work Quality (Superb, Satisfactory, So-so)":"Satisfactory",
   "Transaction Process (Easy, Ok, Difficult)":"Ok",
   "Review":"Reasonable price."
 },
 {
   "Type":"Lawnmover",
   "Name":"Carlos Altilia",
   "Phone":"973-219-3253",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"Akash Gupta",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Reasonable",
   "Work Quality (Superb, Satisfactory, So-so)":"Satisfactory",
   "Transaction Process (Easy, Ok, Difficult)":"Easy",
   "Review":"Using since 2014. Reasonable."
 },
 {
   "Type":"Life Insurance",
   "Name":"Chris Marshal",
   "Phone":"",
   "Email":"christopher.marshall@nm.com",
   "Address":"",
   "Website":"",
   "Recommender":"Akash Gupta",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Reasonable",
   "Work Quality (Superb, Satisfactory, So-so)":"Satisfactory",
   "Transaction Process (Easy, Ok, Difficult)":"Easy",
   "Review":"Good service for life insurance, financial planning etc. Used him to buy life insurance products since around 2012."
 },
 {
   "Type":"Limo/Taxi",
   "Name":"Springfield Limo",
   "Phone":"(973) 218-0040",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"Saurabh Gupta",
   "Service Used":"",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Reasonable"
 },
 {
   "Type":"Limo/Taxi",
   "Name":"Union Taxi",
   "Phone":"(908) 686-1000",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"Wei",
   "Service Used":"",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"good price"
 },
 {
   "Type":"Mortgage Agent",
   "Name":"Shaleen Mahtani, Wells Fargo",
   "Phone":"",
   "Email":"Shaleen.Mahtani@wellsfargo.com",
   "Address":"",
   "Website":"",
   "Recommender":"Akash Gupta",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Value",
   "Work Quality (Superb, Satisfactory, So-so)":"Superb",
   "Transaction Process (Easy, Ok, Difficult)":"Easy",
   "Review":"My first mortgage was from her. Very good service and rates. Lot of people in the friends circle have got mortgage from her."
 },
 {
   "Type":"Mortgage Agent",
   "Name":"Peter Goslin, Citibank",
   "Phone":"",
   "Email":"peter.gostin@citi.com",
   "Address":"",
   "Website":"",
   "Recommender":"Akash Gupta",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Value",
   "Work Quality (Superb, Satisfactory, So-so)":"Satisfactory",
   "Transaction Process (Easy, Ok, Difficult)":"Ok",
   "Review":"Very prompt service and good rates. I refinanced my mortgage from Citi. Got good discount for a new account. Overall, I would say Shaleen is slightly better."
 },
 {
   "Type":"Mortgage Agent",
   "Name":"Sam Joshi",
   "Phone":"732-549-7001",
   "Email":"sjoshi@sdcapitalfunding.com",
   "Address":"1740 Oak Tree Rd, Edison, NJ 08820",
   "Website":"",
   "Recommender":"Saurabh Agarwal",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Value",
   "Work Quality (Superb, Satisfactory, So-so)":"Superb",
   "Transaction Process (Easy, Ok, Difficult)":"Easy",
   "Review":"Good rate and very responsive. Refinance  my mortgage"
 },
 {
   "Type":"Movers",
   "Name":"Ding Dong Movers",
   "Phone":"(718) 539-6669",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"Saurabh Gupta",
   "Service Used":"",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":""
 },
 {
   "Type":"Pediatrician",
   "Name":"Millburn Pediatric",
   "Phone":"(973) 912-0155",
   "Email":"",
   "Address":"159 Millburn Ave. Millburn, NJ 07041 ",
   "Website":"",
   "Recommender":"Akash Gupta",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Reasonable",
   "Work Quality (Superb, Satisfactory, So-so)":"Satisfactory",
   "Transaction Process (Easy, Ok, Difficult)":"Ok",
   "Review":"Decent service. We are using them since 2013."
 },
 {
   "Type":"Painter",
   "Name":"Edwin",
   "Phone":"(908) 337-0726",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"Saurabh Agarwal",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Value",
   "Work Quality (Superb, Satisfactory, So-so)":"Superb",
   "Transaction Process (Easy, Ok, Difficult)":"Easy",
   "Review":"good work. Reasonable price. Flexible to make changes in middle. using for more than 10 years"
 },
 {
   "Type":"Pediatrician",
   "Name":"Stacey C. Tavel, Summit Medical Group Shorthills",
   "Phone":"(973) 379-4496",
   "Email":"",
   "Address":"85 Woodland Rd, Short Hills, NJ 07078",
   "Website":"",
   "Recommender":"Wei",
   "Service Used":"",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Much better than the pediatrician we had previously found from Google search"
 },
 {
   "Type":"Property Insurance",
   "Name":"Rocco, Esposito Insurance",
   "Phone":"973-284-1083",
   "Email":"rocco@espositoinsurance.com",
   "Address":"",
   "Website":"",
   "Recommender":"Saurabh Agarwal",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Reasonable",
   "Work Quality (Superb, Satisfactory, So-so)":"Superb",
   "Transaction Process (Easy, Ok, Difficult)":"Easy",
   "Review":"Using for more than 10 years. Bought home and auto insurances from  him."
 },
 {
   "Type":"Property Insurance",
   "Name":"Rocco, Esposito Insurance",
   "Phone":"973-284-1083",
   "Email":"rocco@espositoinsurance.com",
   "Address":"",
   "Website":"",
   "Recommender":"Akash Gupta",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Value",
   "Work Quality (Superb, Satisfactory, So-so)":"Satisfactory",
   "Transaction Process (Easy, Ok, Difficult)":"Ok",
   "Review":"Good service and price. I get my home and car insurance from Rocco."
 },
 {
   "Type":"Property Insurance",
   "Name":"Rocco, Esposito Insurance",
   "Phone":"973-284-1083",
   "Email":"rocco@espositoinsurance.com",
   "Address":"",
   "Website":"",
   "Recommender":"Saurabh Gupta",
   "Service Used":"",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Good service but you don't get a good deal. Premiums are high but you pay for the service.\n\nPremium up every year."
 },
 {
   "Type":"Real Estate Agent",
   "Name":"Richa Garg",
   "Phone":"973-941-9739",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"Saurabh Agarwal",
   "Service Used":"No",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Prompt and responsive. "
 },
 {
   "Type":"Real Estate Agent",
   "Name":"Richa Garg",
   "Phone":"973-941-9739",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"Akash Gupta",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Reasonable",
   "Work Quality (Superb, Satisfactory, So-so)":"Satisfactory",
   "Transaction Process (Easy, Ok, Difficult)":"Easy",
   "Review":"Prompt and responsive. Now getting very knowledgeable about the area and process. Richa helped me for renting in Short Hills and then for buying must first home. She also helped in getting substitute renter for breaking my rental lease."
 },
 {
   "Type":"Swimming Classes",
   "Name":"YMCA Summit",
   "Phone":"",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"Akash Gupta",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Value",
   "Work Quality (Superb, Satisfactory, So-so)":"Satisfactory",
   "Transaction Process (Easy, Ok, Difficult)":"Easy",
   "Review":"Used swimming classes for both Aditya and Krish. Almost like a regular school."
 },
 {
   "Type":"Tree Service",
   "Name":"Eugene",
   "Phone":"(973) 325-5663",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"Saurabh Gupta",
   "Service Used":"",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":""
 },
 {
   "Type":"Handyman - Wood work",
   "Name":"Nelson",
   "Phone":"(201) 207-6854",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"Saurabh Agarwal",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Reasonable",
   "Work Quality (Superb, Satisfactory, So-so)":"Superb",
   "Transaction Process (Easy, Ok, Difficult)":"Easy",
   "Review":"clean and quality work. very responsible. Reasonable price."
 },
 {
   "Type":"Pediatrician",
   "Name":"Dr. Greunwald",
   "Phone":"(973) 378-7990",
   "Email":"",
   "Address":"90 Millburn Ave #101, Millburn, NJ 07041, USA",
   "Website":"",
   "Recommender":"Sathya Ramakrishna",
   "Service Used":"",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Very good doctor, good service and available on weekends."
 },
 {
   "Type":"Primary care physician",
   "Name":"Kodiyalam Uthra MD",
   "Phone":"(973) 379-9600",
   "Email":"",
   "Address":"55 Morris Ave # 300, Springfield",
   "Website":"",
   "Recommender":"Sathya Ramakrishna",
   "Service Used":"",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Very good doctor and service."
 },
 {
   "Type":"Flooring - Tiles",
   "Name":"Dennis",
   "Phone":"(973) 902-7020",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"Sathya Ramakrishna",
   "Service Used":"",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Good service"
 },
 {
   "Type":"Dentist",
   "Name":"Dental Group of Millburn",
   "Phone":"(973) 376-2700",
   "Email":"",
   "Address":"187 Millburn Ave #1, Millburn, NJ 07041, USA",
   "Website":"",
   "Recommender":"Sathya Ramakrishna",
   "Service Used":"",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Good Service"
 },
 {
   "Type":"Ophthalmologist",
   "Name":"Associates In Ophthalmology",
   "Phone":"(973) 992-5200",
   "Email":"",
   "Address":"22 Old Short Hills Rd, Livingston, NJ 07039",
   "Website":"",
   "Recommender":"Sathya Ramakrishna",
   "Service Used":"",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Very good service"
 },
 {
   "Type":"Plumber",
   "Name":"George Beghyn",
   "Phone":"",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"Sutapa",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Very nice guys..reliable. knows his stuff.\nSudipto - I also recommend him"
 },
 {
   "Type":"Daycare",
   "Name":"Superkids",
   "Phone":"",
   "Email":"",
   "Address":"2 Broad St, Summit, NJ 07901, USA",
   "Website":"",
   "Recommender":"Sutapa",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Good facility, long hours, live feed available to parents. Great location.."
 },
 {
   "Type":"Nanny",
   "Name":"Lily Girma",
   "Phone":"",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"",
   "Service Used":"",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":""
 },
 {
   "Type":"Ophthalmologist",
   "Name":"Scott Walsman at Hudson Eye Physicians",
   "Phone":"973-912-9100",
   "Email":"",
   "Address":"288 Millburn Avenue Millburn, New Jersey 07041",
   "Website":"",
   "Recommender":"Surbhi Gupta",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":""
 },
 {
   "Type":"Kids Summer Camp",
   "Name":"Montclair State University",
   "Phone":"",
   "Email":"",
   "Address":"",
   "Website":"http://www.montclair.edu/gifted/",
   "Recommender":"Akash Gupta",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Premium",
   "Work Quality (Superb, Satisfactory, So-so)":"Superb",
   "Transaction Process (Easy, Ok, Difficult)":"Difficult",
   "Review":"Educational but different. Aditya (2nd grader) attended in 2015 and had classes like \"Brain\" where they dissected sheeps brain. Aditya is attending in 2016 also. Bit expensive though. 3-week full day session is almos $1800 (includes lunch)."
 },
 {
   "Type":"Chess Class",
   "Name":"Wizard of the Mind",
   "Phone":"973-262-1395",
   "Email":"info@wizardsofthemind.com",
   "Address":"379 Morris Avenue, Springfield, NJ 07081",
   "Website":"http://www.wizardsofthemind.com/",
   "Recommender":"Akash Gupta",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"Reasonable",
   "Work Quality (Superb, Satisfactory, So-so)":"Satisfactory",
   "Transaction Process (Easy, Ok, Difficult)":"Easy",
   "Review":"Aditya is attending since 2014. Good classes."
 },
 {
   "Type":"Drycleaning",
   "Name":"Any Garment Cleaners",
   "Phone":"9086888899",
   "Email":"",
   "Address":"2065 Rte 22, Union, NJ 07083, USA",
   "Website":"",
   "Recommender":"Jin",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Good price and good service. $1.99 for most garments. One day pick up."
 },
 {
   "Type":"Tree service",
   "Name":"Save a tree - Ryan Case",
   "Phone":"",
   "Email":"rcase@saveatree.com",
   "Address":"",
   "Website":"",
   "Recommender":"Sutapa",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Great guy. Very helpful. Saved our trees last spring. But the service is expensive."
 },
 {
   "Type":"Attorney",
   "Name":"Law Offices of Eric Wasser",
   "Phone":"908-707-8700",
   "Email":"eric@wasserlaw.com",
   "Address":"1 Veterans Memorial Dr W, Somerville, NJ 08876, USA",
   "Website":"http://www.wasserlaw.jasonwasser.com/",
   "Recommender":"Wei",
   "Service Used":"Yes",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Used for closing house. Seemed quite professional. Fast responses to our questions long even after house was closed. \n \nAttorney:  Eric Wasser\nPhone: 908-707-8700 ext. 130\nEmail: eric@wasserlaw.com\n \nParalegal: Nancy Scherer  ext.134\nEmail: nancy@wasserlaw.com\n \nParalegal:  Carol Bieda ext. 138\nEmail: carol@wasserlaw.com"
 },
 {
   "Type":"Car Service",
   "Name":"Lexus of Route 10",
   "Phone":"973-319-7300",
   "Email":"",
   "Address":"130 ROUTE 10 WEST, WHIPPANY, NJ 07981",
   "Website":"http://www.lexusofroute10.com/",
   "Recommender":"Sudipto",
   "Service Used":"",
   "Cost (Value, Reasonable, Premium)":"",
   "Work Quality (Superb, Satisfactory, So-so)":"",
   "Transaction Process (Easy, Ok, Difficult)":"",
   "Review":"Very professional and prompt"
 },
 {
   "Type":"Electrician",
   "Name":"Mark",
   "Phone":"201-341-7179",
   "Email":"",
   "Address":"",
   "Website":"",
   "Recommender":"Saurabh Agarwal",
   "Service Used":"No",
   "Cost (Value, Reasonable, Premium)":"Reasonable",
   "Work Quality (Superb, Satisfactory, So-so)":"Satisfactory",
   "Transaction Process (Easy, Ok, Difficult)":"Easy",
   "Review":"Used his partner when we moved to our house. Mark can do installation of appliances."
 }
]


@Page({
  templateUrl: 'build/pages/list/list.html'
})


export class ListPage {
  selectedItem: any;
  icons: string[];
  items: Array<{title: string, note: string, icon: string}>;

  constructor(private nav: NavController, navParams: NavParams) {
    // If we navigated to this page, we will have an item available as a nav param
    this.selectedItem = navParams.get('item');

    this.icons = ['flask', 'wifi', 'beer', 'football', 'basketball', 'paper-plane',
    'american-football', 'boat', 'bluetooth', 'build'];

    this.items = [];
    for(let i = 1; i < directory.length; i++) {
      this.items.push({
        title: directory[i].Name,
        note: directory[i].Review,
        icon: this.icons[Math.floor(Math.random() * this.icons.length)]
      });
    }
  }

  itemTapped(event, item) {
    this.nav.push(ItemDetailsPage, {
      item: item
    });
  }
}
